<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!-- Definire i seguenti elementi:
   - elemento root: TEI
   - elementi figli:
        -header (obbligatorio una occorrenza)
        -facsimile (opzionale una occorrenza)
        -text (obbligatorio almeno una occorrenza)
Gli elementi header, facsimile e text hanno tutti un content
model testuale -->

<!DOCTYPE TEI
[
<!ELEMENT TEI (header, facsimile?, text+)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT facsimile (#PCDATA)>
<!ELEMENT text (#PCDATA)>
]>


<TEI>
    <header></header>
    <facsimile></facsimile>
    <text></text>
    <text></text>
</TEI>
