<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!-- Esercizio
root: TEI
Figli:
- header(obbligatorio una volta sola)
- facsimile(opzionale una volta sola)
- testo(obbligatorio una o più volte)
* testo `e un mixed content con possibile elemento <seg>
Attributi:
- header: type:(fixed, CDATA “intestazione”); lang(opzionale,
NMTOKEN)
- facsimile: source:(obbligatorio); ref(optionale, IDREFS)
- testo: id(obbligatorio, ID) type(opzionale contenuto testuale)-->

<!DOCTYPE TEI
[
<!ELEMENT TEI (header, facsimile?, testo+)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT facsimile (#PCDATA)>
<!ELEMENT testo (#PCDATA|seg)*>
<!ELEMENT seg (#PCDATA)>

<!ATTLIST header type CDATA #FIXED "intestazione">
<!ATTLIST header lang NMTOKEN #IMPLIED>
<!ATTLIST facsimile source ID #REQUIRED>
<!ATTLIST facsimile ref IDREFS #IMPLIED>
<!ATTLIST testo id ID #REQUIRED>
<!ATTLIST testo type CDATA #IMPLIED>

]>

<TEI>
    <header type="intestazione" lang="ITA"></header>
    <facsimile source="google.it" ref="ID04"></facsimile>
    <testo id="ID04"></testo>
    <testo id="ID05" type="bambino">Testo seguito da <seg>seg</seg></testo>
</TEI>